// Ground-truth eval set: 5 well-known engineering leaders at private, VC-backed
// dev-tool companies — strong public footprints so the paid services reliably
// return matching data (reliable green PASS on camera).
//
// `groundTruth` is the hand-built set of known-correct facts we score the
// assembled profile against. Kept to high-confidence, stable facts.
// `weight` sums to 100 across the fields in GROUND_TRUTH_WEIGHTS.

export const GROUND_TRUTH_WEIGHTS = {
  name: 10,
  company_name: 15,
  company_domain: 10,
  github_username: 10,
  title_seniority: 8,
  hq_city: 12,
  company_industry: 12,
  company_size_bucket: 8,
  company_type: 5,
  vc_backed: 5,
  recent_activity: 5,
};

export const CANDIDATES = [
  {
    id: "rauch",
    name: "Guillermo Rauch",
    first_name: "Guillermo",
    last_name: "Rauch",
    github_username: "rauchg",
    company_name: "Vercel",
    company_domain: "vercel.com",
    groundTruth: {
      name: "Guillermo Rauch",
      company_name: "Vercel",
      company_domain: "vercel.com",
      github_username: "rauchg",
      title_seniority: "Founder / CEO",
      hq_city: "San Francisco",
      company_industry: "developer tools / cloud infrastructure",
      company_size_bucket: "201-500",
      company_type: "private",
      vc_backed: true,
      recent_activity: true,
    },
  },
  {
    id: "copplestone",
    name: "Paul Copplestone",
    first_name: "Paul",
    last_name: "Copplestone",
    github_username: "kiwicopple",
    company_name: "Supabase",
    company_domain: "supabase.com",
    groundTruth: {
      name: "Paul Copplestone",
      company_name: "Supabase",
      company_domain: "supabase.com",
      github_username: "kiwicopple",
      title_seniority: "Co-founder / CEO",
      hq_city: "San Francisco",
      company_industry: "developer tools / database",
      company_size_bucket: "51-200",
      company_type: "private",
      vc_backed: true,
      recent_activity: true,
    },
  },
  {
    id: "rocha",
    name: "Zeno Rocha",
    first_name: "Zeno",
    last_name: "Rocha",
    github_username: "zenorocha",
    company_name: "Resend",
    company_domain: "resend.com",
    groundTruth: {
      name: "Zeno Rocha",
      company_name: "Resend",
      company_domain: "resend.com",
      github_username: "zenorocha",
      title_seniority: "Founder / CEO",
      hq_city: "San Francisco",
      company_industry: "developer tools / email API",
      company_size_bucket: "11-50",
      company_type: "private",
      vc_backed: true,
      recent_activity: true,
    },
  },
  {
    id: "cramer",
    name: "David Cramer",
    first_name: "David",
    last_name: "Cramer",
    github_username: "dcramer",
    company_name: "Sentry",
    company_domain: "sentry.io",
    groundTruth: {
      name: "David Cramer",
      company_name: "Sentry",
      company_domain: "sentry.io",
      github_username: "dcramer",
      title_seniority: "Co-founder / CTO",
      hq_city: "San Francisco",
      company_industry: "developer tools / observability",
      company_size_bucket: "201-500",
      company_type: "private",
      vc_backed: true,
      recent_activity: true,
    },
  },
  {
    id: "masad",
    name: "Amjad Masad",
    first_name: "Amjad",
    last_name: "Masad",
    github_username: "amasad",
    company_name: "Replit",
    company_domain: "replit.com",
    groundTruth: {
      name: "Amjad Masad",
      company_name: "Replit",
      company_domain: "replit.com",
      github_username: "amasad",
      title_seniority: "Founder / CEO",
      hq_city: "San Francisco",
      company_industry: "developer tools / cloud IDE",
      company_size_bucket: "51-200",
      company_type: "private",
      vc_backed: true,
      recent_activity: true,
    },
  },
];

export const candidateById = (id) => CANDIDATES.find((c) => c.id === id);
